#!/usr/bin/env python
import argparse

usage="Usage: %prog file catalogue [options]"

parser=argparse.ArgumentParser(description='Interpolate stellar atmospheres for usage in spectrum synthesis codes like MOOG.')
#parser = OptionParser(usage=usage)
parser.add_argument("-teff",
					help="Effective Temperature\
					 of the required model",
					 type=float,
					 required=True)

parser.add_argument("-logg",
					help="Surface Gravity (log(g))\
					 of the required model",
					 type=float,
					 required=True)

parser.add_argument("-feh",
					help="Metallicity [Fe/H]\
					 of the required model",
					 type=float,
					 required=True)


parser.add_argument("--modelgrid",
					help="Name of modelgrid default=%(default)s",
					 default="normal")
					 
parser.add_argument("--showgrids",
					help="Show all modelgrids\
					 (available on the web and on disk)",
					 action='store_true')

args = parser.parse_args()


